# Generated by Django 5.2.4 on 2025-08-05 07:57

import student_id_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to=student_id_app.models.unique_photo_path)),
            ],
        ),
    ]
